### ISSUE TITLE
reward 圖，改成用xy map，並且使用jet colormap 代表數值

### ISSUE THREAD

**Issue by itemhsu** [lulu2002/DeepRacerAnalytics#13]
jet colormap
![image](https://user-images.githubusercontent.com/25599185/106538915-0916df80-6538-11eb-8143-9bb7acc38913.png)

有點像這樣
![image](https://user-images.githubusercontent.com/25599185/106539194-83476400-6538-11eb-90da-3286d8dc32b6.png)

**Comment by lulu2002** [comment]
完成！[commit](https://github.com/lulu2002/DeepRacerAnalytics/commit/17e0cf430c861cadb98847c78e1b6650e23f7164)
