### ISSUE TITLE
xy 寬長比要相同

### ISSUE THREAD

**Issue by itemhsu** [lulu2002/DeepRacerAnalytics#15]
![image](https://user-images.githubusercontent.com/25599185/106986849-2d2c2800-67a7-11eb-8791-a7b035430d64.png)

**Comment by lulu2002** [comment]
已修正！現在起不管圖的大小為何，格子長寬比永遠會保持 1:1。[commit](https://github.com/lulu2002/DeepRacerAnalytics/commit/bc94831998afd44dc996ae52d601aaf995f67cb5)
