### ISSUE TITLE
要四捨五入

### ISSUE THREAD

**Issue by itemhsu** [lulu2002/DeepRacerAnalytics#16]
![image](https://user-images.githubusercontent.com/25599185/106987538-a8daa480-67a8-11eb-8a64-50d47374ec10.png)

**Comment by lulu2002** [comment]
已修正！[commit](https://github.com/lulu2002/DeepRacerAnalytics/commit/aac57c9bb5b76388b9e4cfcd5ace3708aa1bcff0)
