### ISSUE TITLE
網站上放置　https://github.com/lulu2002/DeepRacerAnalytics/issues/new　連結

### ISSUE THREAD

**Issue by itemhsu** [lulu2002/DeepRacerAnalytics#20]

**Comment by lulu2002** [comment]
完成！[commit](https://github.com/lulu2002/DeepRacerAnalytics/commit/cf7351dc7c4e28228db99d7b474cd2a1b3441d8a)
![image](https://user-images.githubusercontent.com/41278925/107957179-31441b00-6fdb-11eb-903f-30e99f4300c4.png)
