### ISSUE TITLE
'WORLD_NAME': 'reinvent_base' 才使用reinvent 2018 賽道邊框

### ISSUE THREAD

**Issue by itemhsu** [lulu2002/DeepRacerAnalytics#27]

**Comment by itemhsu** [comment]
![image](https://user-images.githubusercontent.com/25599185/107136597-d3129a80-693f-11eb-8da4-d528ad3a49d7.png)

**Comment by lulu2002** [comment]
完成！[commit](https://github.com/lulu2002/DeepRacerAnalytics/commit/2c9051acda1ef8bf94c9b315934907031eb669b3)
