### ISSUE TITLE
列印hyper parameter

### ISSUE THREAD

**Issue by itemhsu** [lulu2002/DeepRacerAnalytics#28]
![image](https://user-images.githubusercontent.com/25599185/107136712-b9be1e00-6940-11eb-8145-81a2b092380f.png)

**Comment by lulu2002** [comment]
完成！[commit](https://github.com/lulu2002/DeepRacerAnalytics/commit/afd47b726f6ec3c1b0e5dca9f5db249b5a3d759e)
