### ISSUE TITLE
選擇檔案時 tar.gz 反灰，無法選擇

### ISSUE THREAD

**Issue by itemhsu** [lulu2002/DeepRacerAnalytics#30]
![image](https://user-images.githubusercontent.com/25599185/107151509-e2283580-699d-11eb-901b-ca3dade9548b.png)

**Comment by lulu2002** [comment]
暫時先移除了檔案限制，之後會再依照用戶作業系統來做不同類型的支援 [commit](https://github.com/lulu2002/DeepRacerAnalytics/issues/30)
