### ISSUE TITLE
放置參考wp 

### ISSUE THREAD

**Issue by itemhsu** [lulu2002/DeepRacerAnalytics#33]
![image](https://user-images.githubusercontent.com/25599185/107851550-d200d200-6e45-11eb-9bd4-50f62b1731e0.png)

**Comment by lulu2002** [comment]
完成！感謝建議～ [commit](https://github.com/lulu2002/DeepRacerAnalytics/commit/fa85ad1c92fdb0f7319fdd54f9af627453897758)
