### ISSUE TITLE
reinvent 2018 , reinvent 2019 賽道座標

### ISSUE THREAD

**Issue by itemhsu** [lulu2002/DeepRacerAnalytics#36]
公布在
https://github.com/aws-samples/aws-deepracer-workshops/tree/master/log-analysis/tracks

- reInvent2019_track.npy
- reinvent_base.npy

**Comment by lulu2002** [comment]
完成！[commit](https://github.com/lulu2002/DeepRacerAnalytics/commit/2c9051acda1ef8bf94c9b315934907031eb669b3)
