### ISSUE TITLE
來自evluation 的tar.gz 載入之後，沒有結果

### ISSUE THREAD

**Issue by itemhsu** [lulu2002/DeepRacerAnalytics#37]
[line-4m0d21a21-inHigh-fine-cut-4times-evaluation_job_svIeufuYQsm-r3-7f9WhHQ_logs.tar.gz](https://github.com/lulu2002/DeepRacerAnalytics/files/6007220/line-4m0d21a21-inHigh-fine-cut-4times-evaluation_job_svIeufuYQsm-r3-7f9WhHQ_logs.tar.gz)

![image](https://user-images.githubusercontent.com/25599185/108448649-19032300-729d-11eb-8616-a5cd4bcd1e06.png)

應該要像這樣子
![image](https://user-images.githubusercontent.com/25599185/108448759-4780fe00-729d-11eb-9b68-14adf23cbee9.png)

**Comment by lulu2002** [comment]
感謝回報！經實測之後發現是因為 js-untar 在前端解壓縮文件時，會將檔名長度 > 100 的文件重新命名為 %LongLink% 導致分析器無法成功分析資料，這個問題我已研究頗長一段時間，很可惜至今仍找不到解法。

<h2>如何分辨是否因為檔名過長無法分析呢？</h2>
只須使用 Ctrl + Shift + i 打開開發者視窗，並切換到 console tab，如果看到包含 'readAsString' 的錯誤訊息，就帶表示因為檔名過長無法分析。
![image](https://user-images.githubusercontent.com/41278925/117389922-c3dfc080-af1f-11eb-811d-3f1ae3e5fd8a.png)


<h2>以下是一個暫時解決檔名過長無法分析的方式</h2>

1. 使用任何可以打開 .tar.gz 壓縮檔的應用程式，打開車子的分析檔案
![image](https://user-images.githubusercontent.com/41278925/117389829-94c94f00-af1f-11eb-81e2-f14b457530e3.png)
2. 將最上方資料夾任意取一個很短的名字
![image](https://user-images.githubusercontent.com/41278925/117389870-aad70f80-af1f-11eb-8143-db358f5d3e75.png)
3. 重新上傳文件後，檔案即可正常分析。
![image](https://user-images.githubusercontent.com/41278925/117390041-043f3e80-af20-11eb-8b26-50344882e538.png)

**Comment by lulu2002** [comment]
更新：問題如今已解決！不必再自行更改

https://github.com/lulu2002/DeepRacerAnalytics/commit/bb9e79d5f0bfe5be304f1b21ae0f8dfcec57fbf3
