### ISSUE TITLE
SAC 算法產生的 log 無法分析

### ISSUE THREAD

**Issue by itemhsu** [lulu2002/DeepRacerAnalytics#39]
![image](https://user-images.githubusercontent.com/25599185/108644858-a9cf3e00-74eb-11eb-91ab-752a112c4771.png)

log file example

**Comment by lulu2002** [comment]
Now supported.

**Comment by itemhsu** [comment]
Good Jobs

JerryLin ***@***.***> 於 2022年10月7日 週五 凌晨12:18寫道：
