### ISSUE TITLE
yaw圖看看可不可以不要那個大跳躍

### ISSUE THREAD

**Issue by itemhsu** [lulu2002/DeepRacerAnalytics#4]
![image](https://user-images.githubusercontent.com/25599185/106419520-9b18dc80-6493-11eb-8646-656b62008734.png)

**Comment by lulu2002** [comment]
問題已修正！[commit](https://github.com/lulu2002/DeepRacerAnalytics/commit/1e64a1971356169567f6a708162929f8e25aa6b7)
