### ISSUE TITLE
tar.gz無法分析

### ISSUE THREAD

**Issue by itemhsu** [lulu2002/DeepRacerAnalytics#41]
![image](https://user-images.githubusercontent.com/25599185/109265046-df07c300-7840-11eb-9ca8-893527b67163.png)
log 檔案
https://drive.google.com/file/d/14ue9gA27OUK3jqze1WBRQ7WizWEAgHUJ/view?usp=sharing

**Comment by lulu2002** [comment]
問題與解法皆已於 #37 做回應，感謝回報！
