### ISSUE TITLE
圈數 chart里面没有显示數據

### ISSUE THREAD

**Issue by simple365** [lulu2002/DeepRacerAnalytics#53]
![image](https://user-images.githubusercontent.com/2282908/125804493-f6d7b299-dbdf-4fb8-b7aa-dc445b378c2e.png)
圈數 chart里面没有显示數據

**Comment by lulu2002** [comment]
目前分析器暫未支援 SAC 演算法模型的分析，感謝你的回報，會列為未來更新之項目！

**Comment by lulu2002** [comment]
發現與 #39 重覆，先關掉這個
